services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=https://billboard-backend.furqan.codes
    env_file:
      - ./web/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1500:1500"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env 